### ISSUE TITLE
update?

### ISSUE THREAD

**Issue by ServiusTheBearOriginal** [Str3amR/CaptainOfIndustryMods#2]
Does not appear to be working anymore.

**Comment by grimpanda121** [comment]
yeah the cheat menu makes the game not initialize and crashes back to the main menu on loading of map as of 0.4.2

**Comment by Str3amR** [comment]
Hi @ServiusTheBearOriginal and @grimpanda121 ! Thanks for your interest in the mod! Some other people started to make much more interesting mods for the game, One that I am aware of is a fork of this mod, available at https://github.com/altmank/CaptainOfIndustryMods

I invite you to try this one or other mods that are listed on the COI Discord at https://discord.com/invite/JxmUbGsNRU since I have no short term interest into adding features to this mod anyway.

For these reasons, this repo will probably be archived soon.

Thanks again for your interest!
